version: 2

models:
  - name: pii__dim_crm_users
    description: Restricted dimension table containing user PII, located in the pii schema.
    columns:
      - name: user_id
        description: Primary key of the user.
        tests:
          - unique
          - not_null
